function [ponti_foreshock, ponti_mainshock, varargout] = read_fractures_shp(lon_lims, lat_lims, ver_status)
    
    filepath = fullfile('shp_files', 'Surface_Rupture_Ridgecrest_Prov_Rel_1.shp');
    
    if (exist('lat_lims','var')) && (~isempty(lat_lims))
        mask = true;
    else
        mask = false;
    end
    
    string_ver1 = "Yes";
    string_ver2 = "Partial";
    if (exist('ver_status','var'))
        if (strcmp(ver_status,'Partial'))
            string_ver1 = string_ver2;
        elseif (strcmp(ver_status,'Yes'))
            string_ver2 = string_ver1;
        end
    end
    
    switch mask
        
      case true
        
        %% Importing fracture lines from Ponti et al. (2020)
        % Fractures are filtered by origin (tectonic, to avoid uncertain or shaking
        % origins) and event source (foreshock or mainshock)
        % Source: https://www.sciencebase.gov/catalog/item/5ef132f282ced62aaae18faa
        
        boundaries = [lon_lims(1), lat_lims(1); lon_lims(2), lat_lims(2)];
        
        ponti_foreshock = shaperead(filepath,...
                                    'UseGeoCoords',true,...
                                    'BoundingBox',boundaries,...
                                    'Selector', ...
                                    {@(frac_source, frac_origin, verified)...
                                    (strcmp(frac_source,'Mw 6.4')) &&...
                                    (strcmp(frac_origin,'Tectonic')) &&...
                                    ((strcmp(verified,string_ver1)) || (strcmp(verified,string_ver2))),...
                                    'Source','Origin','Verified'});
        
        ponti_mainshock = shaperead(filepath,...
                                    'UseGeoCoords',true,...
                                    'BoundingBox',boundaries,...
                                    'Selector', ...
                                    {@(frac_source, frac_origin, verified, classification)...
                                    (strcmp(frac_source,'Mw 7.1')) &&...
                                    (strcmp(frac_origin,'Tectonic')) &&...
                                    ((strcmp(verified,string_ver1)) || (strcmp(verified,string_ver2))),...
                                    'Source','Origin','Verified','Class'});

        
      case false

        
        %% Importing fracture lines from Ponti et al. (2020)
        % Fractures are filtered by origin (tectonic, to avoid uncertain or shaking
        % origins) and event source (foreshock or mainshock)
        ponti_foreshock = shaperead(filepath,...
                                    'UseGeoCoords',true,...
                                    'Selector', ...
                                    {@(frac_source, frac_origin, verified)...
                                    (strcmp(frac_source,'Mw 6.4')) &&...
                                    (strcmp(frac_origin,'Tectonic')) &&...
                                    ((strcmp(verified,string_ver1)) || (strcmp(verified,string_ver2))),...
                                    'Source','Origin','Verified'});
        
        ponti_mainshock = shaperead(filepath,...
                                    'UseGeoCoords',true,...
                                    'Selector', ...
                                    {@(frac_source, frac_origin, verified)...
                                    (strcmp(frac_source,'Mw 7.1')) &&...
                                    (strcmp(frac_origin,'Tectonic')) &&...
                                    ((strcmp(verified,string_ver1)) || (strcmp(verified,string_ver2))),...
                                    'Source','Origin','Verified'});
        
    end

    ponti_foreshock = calc_UTM(ponti_foreshock);
    ponti_mainshock = calc_UTM(ponti_mainshock);
    rodriguez_all = calc_UTM(rodriguez_all);
    
end
